#!/bin/bash
abc=abcdefghijklmnopqrstuvwxyz; i=0; while [ $i -lt 26 ]; do j=0; while [ $j -lt 26 ]; do x=${abc:$i:1}${abc:$j:1}; if [ "$x" != "oo" ]; then echo $x; fi; j=$((j+1)); done; i=$((i+1)); done
